### ISSUE TITLE
confidence interval for an effect size in a repeated-measures ANOVA?

### ISSUE THREAD

**Issue by dmurphy8** [jasp-stats/jasp-issues#1299]
* Enhancement: is there a way to get a confidence interval for effect sizes in a repeated-measures ANOVA? 
* Purpose: compare the magnitude of effects 
* Use-case:

**Is your feature request related to a problem? Please describe.**
 

**Describe the solution you'd like**
 You can get a confidence interval for Cohen's d in t-tests so is there a way to do it in an ANOVA?

**Describe alternatives you've considered**
 

**Additional context**

**Comment by juliuspf** [comment]
@dmurphy8, from what I make of this, the issue is fixed in a recent JASP version? Can you confirm this?

**Comment by dmurphy8** [comment]
No, I don’t see an option for it. How would I do it?

**Comment by juliuspf** [comment]
If you go to Post-hoc tests there is a box for confidence interval. Does that help?
![Screenshot 2022-11-09 at 10 50 42](https://user-images.githubusercontent.com/38500953/200798044-c6d4f833-c779-436d-9db7-be1f8712434d.png)

**Comment by juliuspf** [comment]
This issue was fixed by https://github.com/jasp-stats/jaspAnova/pull/90.

**Comment by dmurphy8** [comment]
Yes, that’s great! But you still can’t do it for the main effects or interaction effect sizes.

**Comment by juliuspf** [comment]
@JohnnyDoorn?

**Comment by JohnnyDoorn** [comment]
Hi @dmurphy8 ,

Do you mean confidence intervals for the omega/eta effect sizes in the main ANOVA table?

Cheers
Johnny

**Comment by dmurphy8** [comment]
Yes!

**Comment by tomtomme** [comment]
This R-Package may be of help implementing this: https://easystats.github.io/effectsize/

**Comment by dmurphy8** [comment]
Awesome thanks! Happy new year!

**Comment by TarandeepKang** [comment]
Hi all,

I was just coming here to suggest this. I've just seen a new paper on omega squared in Psychological Methods with advice on the best approaches for calculating confidence intervals for it, and they suggest formulae and implementations on Ken Kelley's MBESS package so maybe give that one and the (very good) new paper a look? 

Kelley, K. (2007). Confidence Intervals for Standardized Effect Sizes: Theory, Application, and Implementation. Journal of Statistical Software, 20, 1–24. https://doi.org/10.18637/jss.v020.i08
Kroes, A. D. A., & Finley, J. R. (2023). Demystifying omega squared: Practical guidance for effect size in common analysis of variance designs. Psychological Methods. https://doi.org/10.1037/met0000581
Steiger, J. H. (2004). Beyond the F Test: Effect Size Confidence Intervals and Tests of Close Fit in the Analysis of Variance and Contrast Analysis. Psychological Methods, 9(2), 164–182. https://doi.org/10.1037/1082-989X.9.2.164

**Comment by JohnnyDoorn** [comment]
@TarandeepKang and @dmurphy8 I am currently implementing some CI's for effect sizes in (RM) ANOVA, specifically the partial eta and omega effect sizes based on the effectsize package - would that suffice?

**Comment by dmurphy8** [comment]
Yes, that’d be amazing! Something just like how you can do it for the t-test would be great. Thanks!

Dillon

￼

**Comment by TarandeepKang** [comment]
Hi @JohnnyDoorn. Yes sounds great but I would definitely recommend following  

Kroes, A. D. A., & Finley, J. R. (2023). Demystifying omega squared: Practical guidance for effect size in common analysis of variance designs. Psychological Methods. https://doi.org/10.1037/met0000581

because omega seems a bit of a minefield?

Best,

Tarandeep

**Comment by JohnnyDoorn** [comment]
@TarandeepKang Thanks - I took a closer look and saw that these CI methods cannot safely generalize to RM ANOVA. I asked the package maintainer for some insight on how to best resolve it. In the meantime, I will implement the CI's in the AN(C)OVA. Both MBESS and effectsize seem to use the same non-central algorithm for the CI, so we are good there.

**Comment by JohnnyDoorn** [comment]
will leave this open for RM ANOVA CI's
