### ISSUE TITLE
[Bug]: Lagging when attempting to save or export results 

### ISSUE THREAD

**Issue by mvaliadis** [jasp-stats/jasp-issues#1586]
### JASP Version

0.16

### What analysis are you seeing the problem on?

Linear regression, ANOVA

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I recently installed JASP version 0.16.0 and there appears to be a significant lag when attempting to save or export a result. I recorded the behavior on a different dataset to verify that I can replicate the bug and it still occurs. Below are screenshots from my attempt to export my results in PDF form which started at 8:52 (top screenshot) and lasted until 18:07 (below screenshot). This actually pales in comparison to my issue from over a week ago which took roughly 1 hour to save which I didn't record. 

![export_results_init](https://user-images.githubusercontent.com/54821923/150976704-b45cd897-3595-4d5e-a82a-027f88e8eb1b.png)

![export_results_fin](https://user-images.githubusercontent.com/54821923/150976797-81f2ee9c-e5e7-458b-a385-ecea0dd2c40d.png)
 

### Expected Behaviour

I have also tried replicating this problem with a Linux based operating system (Ubuntu 20.04), to no avail. When run on Ubuntu, the analyses were saved and exported almost instantly with no lag. 

### Steps to Reproduce

1. Load data
2. Perform generic descriptive stats of your choosing 
3. Perform basic linear regression analysis 
4. Try to export or save results
...
[whale_zip.zip](https://github.com/jasp-stats/jasp-issues/files/7933613/whale_zip.zip)

[whalespeed.csv](https://github.com/jasp-stats/jasp-issues/files/7933543/whalespeed.csv)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Does this problem only occur when you export to PDF? Or also with HTML?
I cannot reproduce it on my mac, and I have now no access to Windows. Maybe can @JorisGoosen try to reproduce it?

**Comment by JorisGoosen** [comment]
This sounds quite similar to https://github.com/jasp-stats/jasp-issues/issues/1496, which means https://static.jasp-stats.org/JASP-Qt6-Testing-2.zip might solve it.

If that works then it we will have a version out soon that should fix it.

**Comment by juliuspf** [comment]
Hi @mvaliadis, does this issue persist with the latest JASP version?
