### ISSUE TITLE
[Bug]: Error in diag(scales) %*% truevar: non-conformable arguments

### ISSUE THREAD

**Issue by saggnev** [jasp-stats/jasp-issues#2294]
### JASP Version

0.18.0

### JASP Module

Factor

### What analysis are you seeing the problem on?

Confirmatory factor analysis

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When I check Reliability (under Additional Output) the right panel is grayed-out and the attached is displayed.
![image_2023-09-19_135424920](https://github.com/jasp-stats/jasp-issues/assets/92183852/3cd1b7d4-8928-45b0-b9b0-6edb2d59899e)

### Expected Behaviour

Not sure because this was the first time I tried it. But, I assume that it should show one or more measures of construct reliability.

### Steps to Reproduce

1. Open a CSV file with multiple columns associated with 2 or more scales.
2. Select Confirmatory Factor Analysis.
3. Select the columns into the factors.
4. Click on Additional Output and check Reliability.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspfadt** [comment]
@saggnevm thanks for reporting this bug. I suspect the issue is within the `semTools` package. Unfortunately, without the data file and the model syntax, I cannot find out what is going wrong. Any chance you could share that?

**Comment by saggnev** [comment]
The data file is attached. Here's the syntax (the problem occurs when
reliability = TRUE):

jaspFactor::confirmatoryFactorAnalysis(

version = "0.18",

ave = TRUE,

factors = list(list(indicators = list("I am willing to select a challenging
work assignment that I can learn a lot from.", "For me, development of my
work ability is important enough to take risks.", "I often look for
opportunities to develop new skills and knowledge.", "I enjoy challenging
and difficult tasks at work where I'll learn new skills."), name =
"Factor1", title = "Factor 1"), list(indicators = list("I like to show that
I can perform better than my coworkers.", "I like to work on projects where
I can prove my ability to others.", "I try to figure out what it takes to
prove my ability to others at work.", "I enjoy when others at work are
aware of how well I am doing."), name = "Factor2", title = "Factor 2"),
list(indicators = list("At work, avoiding a show of low ability is more
important to me than learning a new skill.", "I would avoid taking on a new
task if there was a chance that I would appear rather incompetent to
others.", "I prefer to avoid situations at work where I might perform
poorly.", "I'm concerned about taking on a task at work if my performance
would reveal that I had low ability."), name = "Factor3", title = "Factor
3")),

htmt = TRUE,

naAction = "pairwise",

packageMimiced = "Mplus",

*reliability = TRUE*)

**Comment by juliuspfadt** [comment]
ah well, I was imprecise about the requirements. So what I need is a screenshot of how you specify the factors. And you probably tried attaching the data to an email. That does not work. You have to upload to the GitHub website where you made the issue.

**Comment by saggnev** [comment]
[Construct validity.csv](https://github.com/jasp-stats/jasp-issues/files/12673884/Construct.validity.csv)
![Factors](https://github.com/jasp-stats/jasp-issues/assets/92183852/bea880cc-f9fa-4cd3-aedb-e253d573dbde)

**Comment by juliuspfadt** [comment]
Thanks :) so this is an issue in the r-package `semTools`, which we use to compute the reliability. I have made an issue at their GitHub site https://github.com/simsem/semTools/issues/130. Let's see how that works out. For the time being I can only advise you to treat your variables as quasi-continuous. That means, you may change the scale of these in JASP to "scale" and the analysis should run smoothly.

**Comment by juliuspfadt** [comment]
Once the new semTools version is on CRAN this issue will be fixed.

**Comment by saggnev** [comment]
Thank you.

**Comment by saggnev** [comment]
Can you tell me where I can change the scale to "scale"?

**Comment by juliuspfadt** [comment]
see https://jasp-stats.org/getting-started/ "change variable types"

**Comment by saggnev** [comment]
Got it.

**Comment by tomtomme** [comment]
@saggnev 
Can you re-test this with jasp 0.18.3 to confirm this is fixed?
Thx!

**Comment by SoLarStud** [comment]
Same problem, sorry, this is my first time on GitHUb so I don't know if I'm doing my request properly.
I'm on Windows 10, Jasp 0.18.3

Error Message : 
This analysis terminated unexpectedly. 
Error in diag(scales) %*% truevar: non-conformable arguments
Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])
doTryCatch(return(expr), name, parentenv, handler)
withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)
analysis(jaspResults = jaspResults, dataset = dataset, options = options)
.cfaTableReliability(jaspResults, options, cfaResult)
semTools::compRelSEM(cfaResult[['lav']], return.total = TRUE)
omegaCat(truevar = commonCov, denom = totalCov, threshold = threshold[[b]][myIndNames], scales = latScales[[b]][myIndNames])

**Comment by tomtomme** [comment]
This is probably fixed in the upcoming version 0.19. if you need this now you can test it via a nightly build 
https://static.jasp-stats.org/Nightlies/

**Comment by SoLarStud** [comment]
Thank you so much for your answer. Seems like a Christmas present to me. Cant's try it right now, but I'll try it this week and will let you know. Many thanks.

**Comment by juliuspfadt** [comment]
It is not fixed, because `semTools` has not yet updated on CRAN.

**Comment by tomtomme** [comment]
Still not fixed upstream. 
File to test 
[Construct.validity.jasp.zip](https://github.com/user-attachments/files/18049534/Construct.validity.jasp.zip)

**Comment by juliuspfadt** [comment]
makes sense, since `semTools` is still not updated on CRAN.

**Comment by juliuspfadt** [comment]
we could switch to using the GitHub version of semTools. We should come back to this prior to the next release and see if semTools is update until then

**Comment by juliuspfadt** [comment]
Okay, so I decided not to wait any longer for semTools to update on CRAN but use the GitHub version, lets hope this does not become unstable.
