### ISSUE TITLE
[Bug]: No help file with Flexplot-Clone and Distribution-Clones

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2677]
### JASP Version

Others

### Commit ID

97f99295e463d69df042fdb741c910dfcc0d1d3a

### JASP Module

Descriptives, Learn Stats

### What analysis are you seeing the problem on?

Flexplot, all from Learn Stats

### What OS are you seeing the problem on?

Flatpak

### Bug Description

![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/c29c7e2f-d970-4bdc-83c1-cef630242fc5)

Empty help file when flexplot is started from descriptives module. All is fine, when flexplot is started from visual modeling. Same for the distribution modules when started from "Learn Stats".

Strangely help is available for the time series clone when started from descriptives, so its not a general problem for all cloned modules.

### Expected Behaviour

help available

### Steps to Reproduce

1. Start Flexplot from descriptives 
2. open help

### Log (if any)

-------- Application Info --------
JASP Version: JASP 0.19
Build Branch: HEAD
Build Date: Apr 22 2024 12:56:16 (Netherlands)
Last Commit: 97f99295e463d69df042fdb741c910dfcc0d1d3a

-------- Basic Info --------
Operating System: KDE Flatpak runtime
Product Version: 6.5
Kernel Type: linux
Kernel Version: 6.6.26-1-MANJARO
Architecture: x86_64
Install Path: /app/bin
System Local: de_DE

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
And the spacing of the help files title seems off:
![Screenshot_20240423_093517](https://github.com/jasp-stats/jasp-issues/assets/4428185/530adbf2-2ca0-48f6-99b2-1efeb7ef2ab0)

**Comment by shun2wang** [comment]
> And the spacing of the help files title seems off:

Thanks for the report, it only in nightly build and will fixed in the next release.

**Comment by boutinb** [comment]
I will use the info QML properties to generate the help file.

**Comment by tomtomme** [comment]
Still an issue with: 
-------- Application Info --------
JASP Version: JASP 0.19
Build Branch: HEAD
Build Date: May  1 2024 13:02:38 (Netherlands)
Last Commit: 4825b388f588478d5e4fae448240ab5ded435d86

-------- Basic Info --------
Operating System: KDE Flatpak runtime
Product Version: 6.5
Kernel Type: linux
Kernel Version: 6.6.26-1-MANJARO
Architecture: x86_64
Install Path: /app/bin
System Local: de_DE

**Comment by tomtomme** [comment]
works with yesterdays beta :)

**Comment by tomtomme** [comment]
premature... works for flexplot, but not yet for Learn Stats => Distribution Clone

**Comment by boutinb** [comment]
Done with https://github.com/jasp-stats/jasp-desktop/pull/5504
