### ISSUE TITLE
[Crash]: Mark Cochrane Meta-Analysis as Beta

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#3256]
### JASP Version

0.95.4

### JASP Module

Cochrane Meta-Analyses

### What analysis are you seeing the problem on?

all 4

### What OS are you seeing the problem on?

Flatpak on all my systems (2 desktops, laptops)

### Bug Description

As soon as I select a variable to do the meta-analyses jasp is freezing. Sometimes earlier (when result tables are still empty), sometimes later (when already some parts of the results are displayed). In all cases the whole interface is not clickable anymore and the spinning circles in the result window stop spinning.

### Expected Behaviour

cochrane should work

### Steps to Reproduce

1. open any cochrane analysis
2. select any topic
3. select any variable and wait for the crash or freeze

**Comment by tomtomme** [comment]
just tested with latest beta. Still relevant

-------- Application Info --------
JASP Version: JASP 0.95
Build Branch: HEAD
Build Date: Jul  3 2025 10:18:36 (Netherlands)
Last Commit: 9b32eeaba4462b0cf208cfb3274125882646ab36

-------- Basic Info --------
Operating System: KDE Flatpak runtime
Product Version: 6.8
Kernel Type: linux
Kernel Version: 6.15.6-1-MANJARO
Architecture: x86_64
Install Path: /app/bin
Platfotm Name: wayland
System Local: de_DE

**Comment by boutinb** [comment]
I get sometimes a crash (in debug mode, not in release mode) in the QML Engine self (deep in the Qt code).
I think now I cannot do so much: just ask the user to have a robust machine.
When we upgrade to Qt 6.9, hopefully this version will cope better with such a situation.

**Comment by tomtomme** [comment]
should we mark the module as "beta" as long as this problem exists? It still exists with 0.95.3 on a very robust machine with 1gbit internet - and we are already using Qt 6.9 I think?

-------- Application Info --------
JASP Version: JASP 0.95.3
Build Branch: HEAD
Build Date: Oct  1 2025 11:30:26 (Netherlands)
Last Commit: b84b1164a159f6f475d847143c8643258e5e2488

-------- Basic Info --------
Operating System: KDE Flatpak runtime
Product Version: 6.9
Kernel Type: linux
Kernel Version: 6.12.48-1-MANJARO
Architecture: x86_64
Install Path: /app/bin
Platform Name: wayland
System Local: de_DE

**Comment by tomtomme** [comment]
Good solution!

**Comment by tomtomme** [comment]
Also next week I could set up a new project board. Best would be to just rename the 0.95.3 project to 0.9X and move only the "Done" items to a new 0.95.3 board. Would that helpt / be okay?

**Comment by boutinb** [comment]
> Also next week I could set up a new project board. Best would be to just rename the 0.95.3 project to 0.9X and move only the "Done" items to a new 0.95.3 board. Would that helpt / be okay?

Yes I think this is a good solution. Thanks!

**Comment by tomtomme** [comment]
@boutinb 
it is not there yet: https://jasp-stats.org/known-issues/

**Comment by boutinb** [comment]
Ah yes, I forgot. A message like 'Warning: on some systems this analysis can be really slow, so slow that JASP does not respond anymore."

**Comment by tomtomme** [comment]
I think that message would be fine :)

**Comment by boutinb** [comment]
Done

**Comment by tomtomme** [comment]
mmh, I still cannot find the note here: https://jasp-stats.org/known-issues/

**Comment by tomtomme** [comment]
closing since we now have a link to all bugs on the known issues page
