### ISSUE TITLE
[Bug]: Cross-platform inconsistencies in Model-based Clustering

### ISSUE THREAD

**Issue by LucasMolleman** [jasp-stats/jasp-issues#3677]
### JASP Version

0.95.1

### JASP Module

Machine Learning

### What analysis are you seeing the problem on?

Model-Based Clustering

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Hi JASP team,

Thanks for making this great software - I love it!

[strangesituation_student.zip](https://github.com/user-attachments/files/22252917/strangesituation_student.zip)

When running a cluster analysis, it seems that different versions of JASP yield different results. For example, I was sent a JASP file by a student (attached; data is fictitious) whose results did not match up with the answer sheet in the assignment of our EBCP course at UvA. 

Indeed I saw deviating results for running Max. 3 clusters. However, when re-running the analysis I recovered my results (which were in the answer sheet). I run JASP version 0.95.1.

When I re-run the analyses in the version from the UvA software center (v. 0.19.3.0) I get again slightly different results when asking for max 6 clusters (which was the other question in my assignment).

Best wishes, also on behalf of Hilde,
Lucas

### Expected Behaviour

The same clustering results across JASP versions.

### Steps to Reproduce

1. open the JASP file in v. 0.95.1 and see what results the student had obtained (presumably in an older version of JASP, but this we don't know - I will update you when I find this out).
2. re-run the same analysis
3. check clustering results.

### Final Checklist

- [x] I have included a screenshot showcasing the issue, if possible.
- [x] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [x] I have accurately described the bug, and steps to reproduce it.

**Comment by koenderks** [comment]
Hi,

What exactly is different? We did fix this issue (https://github.com/jasp-stats/jasp-issues/issues/3297) in this pull request (https://github.com/jasp-stats/jaspMachineLearning/pull/423), which impacts the cluster means table and plot. Is your issue related to that? Some elaboration on the exact mismatches is appreciated.

**Comment by koenderks** [comment]
Are you on a different OS than your student?

**Comment by LucasMolleman** [comment]
for me it DOES update (from screenshot 1 to screenshot 2)! I will try to find out about the OS of the student (who is not responding atm).

**Comment by koenderks** [comment]
Okay, maybe @vandenman can share his insights into if different OS's can produce different results with the same seed?

**Comment by LucasMolleman** [comment]
I just received a reply from the student to my question. Both the student and I work in Windows.

**Comment by bbabac** [comment]
We receive the first screensot where the second cluster has 222 data samples when running JASP on Macbook Pro, but receive the second screenshot where the second cluster has 426 data samples when running on Windows laptop.
Laptops are side by side and the same options are selected on both.

**Comment by HildeHui** [comment]
Such algorithms always depend on starting values. The link Koen posted illustrates how these are determined. A maybe handy, but not fast solution, is that the default in JASP is to restart with different starting values, either via a reordering of variables or with different seeds.

**Comment by koenderks** [comment]
If you currently open a clustering analysis in JASP then the seed is not ticked by default, which means that there is no seed applied at all and results will be random.

**Comment by HildeHui** [comment]
Many thanks for working on this!

At the top of this thread is a file: strange situation.zip. Maybe it helps if you run it several times, e.g. with different ordering of input variables or different platforms. I'm sorry I do not have time to do it myself right now.

There were inconsistencies dependent on many things: platforms but for example also the order in which variables were entered.
This is because mixture algorithms compute starting values. See your comment September 11.

A solution would be if the JASP algorithm runs e.g. 100 times with different ordering of input variables, and then only reports the solution with e.g. the lowest BIC.

**Comment by tomtomme** [comment]
@vandenman 
any update on this one? Was the bug fixed in the parent R package or is there an issue on this on their github tracker that we can follow for updates?

**Comment by HildeHui** [comment]
hi all,
thank you very much for looking into this.

The issue is still there. In our course about 90 students ran the analysis on a variety of platforms, and many got different results. 
A solution would be if JASP runs the algorithm e.g. 100 times with different ordering of input variables or different seeds, and then only report the solution with the lowest BIC (or whatever criterion the user wants).
It is an issue which most likely due to mclust itself, which is dependent on starting values. Therefore I guess people running R code typically restart mclust repeatedly.

If this is not scalable in JASP, maybe it is worthwhile to have a warning somewhere.
Hilde
