### ISSUE TITLE
BAIN model hypotheses errors

### ISSUE THREAD

**Issue by lindeloev** [jasp-stats/jasp-issues#380]
Congratulations on a successful release of JASP 0.10! I noted two issues with the BAIN module hypothesis specification:

It throws an error if you do two different hypotheses involving the same variable having two different values. E.g., the second line in each of the following causes it to fail:

    Extraversion = 0
    Extraversion = 0.2
    
    -0.2 < Extraversion < 0.2
    -0.3 < Extraversion < 0.3

It works just fine if you do the same hypothesis twice and/or have different hypotheses. So this is OK:

    Extraversion = 0
    Neuroticism = 0
    Extraversion = 0 & Neuroticism = 0

Perhaps related, it throws an error if there are two empty lines. E.g.,

    Extraversion = 0
    [empty]
    [empty]

This can be hard to debug for the newcomer.

JASP 0.10
Windows 10, 64bit

**Comment by koenderks** [comment]
@TimKDJ Maybe we can close this issue since it was fixed in a previous release of JASP/bain. Might double-check after merging the latest pull request though, just for assurance.

**Comment by TimKDJ** [comment]
> It throws an error if you do two different hypotheses involving the same variable having two different values. 

This is not fixed yet.. It might be worthwhile to make the package maintainers aware of that issue instead of us solving it though

**Comment by koenderks** [comment]
The bain package returns an informed error when this happends:

![image](https://user-images.githubusercontent.com/25059399/71780232-36552f00-2fc0-11ea-9025-a0c9b0543bfd.png)
