### ISSUE TITLE
Post Hoc test Repeated Measures ANOVA

### ISSUE THREAD

**Issue by BiomechFlo** [jasp-stats/jasp-issues#459]
Hi,
I just worked on an old project and wanted to check the statistics. I did a Repeated Measures ANOVA (2 factors, 2 and 5 levels) including Bonferroni-Holm corrected Post-Hoc Tests using the JASP Version 0.10.2. The outcome of the Post-Hoc tests looked weird. I always got the same results (Mean Difference, SE, t, pholm) for the different comparisons. I repeated the analysis using JASP Version 0.9.1. The results for the ANOVA were identical whereas the results for the Post-Hoc Tests made much more sense. Could it be that there is something broken with the Post-Hoc Test in JASP version 0.10.2 doing repeated measures ANOVA?
I attached three files (RMA.zip):
oxy_con_new.jasp (analysis with JASP Version 0.10.2)
oxy_con_old.jasp (analysis with JASP Version 0.9.1)
slope_array.csv (data for analysis)
I am using a WIN7 PC (64bit system)
Kind regards Flo
[RMA.zip](https://github.com/jasp-stats/jasp-issues/files/3526490/RMA.zip)

**Comment by TimKDJ** [comment]
@JohnnyDoorn can you check this out?

**Comment by JohnnyDoorn** [comment]
Hi Flo,
I think this is related to pooling the error term for post hoc tests in the RM ANOVA. I just finished rewriting the code, and it is now fixed! Thanks for reporting this - please reopen if you have any additional questions.
Kind regards
Johnny

**Comment by BiomechFlo** [comment]
Hey Johnny,

I just upgraded to JASP Version 0.11.1 but still get wrong numbers for the post hoc tests of the RM ANOVA. I attached the JASP file.

Kind Regards 
Flo
[Updated_version.zip](https://github.com/jasp-stats/jasp-issues/files/3703401/Updated_version.zip)

**Comment by JohnnyDoorn** [comment]
Hi FLo,

Yes, that's correct - unfortunately the rewritten ANOVA will only be in the
next release (we want to merge all rewrites simultaneously so that the
transition is smooth and manageable). It will be released in a month or so.

Kind regards
Johnny
