### ISSUE TITLE
repeated measures ANOVA bugs

### ISSUE THREAD

**Issue by Iggy1gnasiak** [jasp-stats/jasp-issues#691]
* JASP version: 0.12.1

* OS name and version: Windwos 10 Enterprise (Version: 1607)
* Analysis: repeated measures ANOVA
* Bug description: 

1.) I have encountered an error message running a repeated measures ANOVA in JASP 0.12.1. However, I was able to run the analysis in the previous JASP release (not sure, some 0.11. release). Please see the attached screenshot (OneWay_repANOVA.jpg) for the description.

2.) I then tried another dataset to see what happens. Here, the analysis ran, however, it seems the descriptive plot does not scale accurately. Please see the plot in: TwoWay_repANOVA.jpg. 
* Expected behaviour:

1.) Is there something funky in the dataset (attached: oneWay_data.csv) that correctly causes this behavior? Or should the analysis compute?

2.) I guess the plot should just use more reasonable y-axis scaling. That was beautiful in the last release. 

#### Steps to reproduce:
1. I attached the data for both issues. For 1.) oneWay_Data.csv. For 2.) twoWay_data.csv 
2. -> 1.) Using oneWay_Data.csv: run a repeated measures ANOVA, with three levels (Pronation, Neutral, Supination). 
-> 2.) Using twoWay_Data.csv: run a two-way repeated ANOVA, with three within levels: Walk01, WalkSM, WalkFS; and the variable "Group" as between subject factor. Use the descriptive plot function, with horizontal axis: within factor and separate lines: Group
[JASP_bugs.zip](https://github.com/jasp-stats/jasp-issues/files/4518058/JASP_bugs.zip)

**Comment by boutinb** [comment]
The first issue is solved in the next release (maybe today, but you can try it already here: http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-v0.12.2.0-25e87a67897e2764ea8097d400dd483190cb8af4.msi)
The second issue, @JohnnyDoorn has to have a look.

**Comment by JohnnyDoorn** [comment]
@vandenman 
The issue is that we add and subtract 1 from the max and min of the dependent variable (around line 1471 in commonAnovaBayesian), respectively, if I remove this then the plot scales well again - should I just remove that? I think we did this a while ago so that it looks a little nicer (i.e., that there is some extra whitespace in the plot), but I don't think this aesthetic advantage holds in these cases - what do you think?

**Comment by JohnnyDoorn** [comment]
Ok, this is now fixed in https://github.com/jasp-stats/jasp-desktop/pull/4053

**Comment by Iggy1gnasiak** [comment]
Hi @boutinb and @JohnnyDoorn!

Thanks for being so super responsive. That is nice! I just downloaded JASP again but the error is still present. Also, the version number is still the same (0.12.1). I guess you have not made a new release yet, correct?

Just so I know when I can continue. Do you have a rough estimate when you would make a new release? Also, can I expect that the version number will change? 

Thank you very much for your support! I am using JASP for teaching at it is a super amazing software you have there!
Thanks

niklas

**Comment by JohnnyDoorn** [comment]
Hi @Iggy1gnasiak 

Can you try this nightly build?
http://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-v0.12.2.0-eca7e082cdfa0ebf7c375a739ce6ad37fa4a4775.zip
Or here for the msi file:
http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-v0.12.2.0-eca7e082cdfa0ebf7c375a739ce6ad37fa4a4775.msi

The release with the fixes will follow shortly, but for now I think this version has the fixes already.

Cheers
Johnny

**Comment by Iggy1gnasiak** [comment]
Hi @JohnnyDoorn 

I tried the nightly build, it all works perfectly. Thanks!
I was just asking about the release since I use JASP for teaching and I want to make sure the students install a version that will run the examples I am preparing. I expect students will start installing around the 4th of May. Do you think the release will be online by then? Or do I need to set up an alternative way of distributing the nightly build?
Thanks!

niklas

**Comment by JohnnyDoorn** [comment]
I think the new release (with those fixes) is currently being uploaded to our website, so that will definitely be in time for your students!
