### ISSUE TITLE
Mangled name in 0.13

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#851]
In the table note for the Analysis of Effects -- Matched models (Bayesian ANOVA's) we say:
"Analysis suggested by Sebastiaan Matht" His last name is "Mathot", with an "accent circumflex" on the o, so "o-dakje". So this entire letter dropped out. In addition to correcting this, maybe we can include it in a unit test, because this is not the first time we experience this issue.

![image](https://user-images.githubusercontent.com/8603015/86591962-d2251f00-bf92-11ea-80e6-6ad2426cc726.png)

**Comment by JorisGoosen** [comment]
This probably got lost somewhere in all the translation stuff. I remember seeing this name come by in several different forms, I think all somehow with the "o-dakje" but why it eventually disappeared is a good one.

**Comment by FransMeerhoff** [comment]
Not reproducible on 0.13.1
@JorisGoosen : Agree?

**Comment by JorisGoosen** [comment]
Have you tried Windows?

**Comment by JorisGoosen** [comment]
On linux it looks good btw.

**Comment by FransMeerhoff** [comment]
On Windows indeed not good. But the translation differs there anyway 'Beschrijvend' instead of 'Beschrijvende statistiek' ??
I'll  have a look

**Comment by JorisGoosen** [comment]
But after you build, is the .po file changed? (Aka with generating of language files?)

because in that case you could push the change and we can see if a new nightly has it fixed.

**Comment by FransMeerhoff** [comment]
Changing the Unicode flag on the Windows build machine solves this issue.
@FBartos Could you check this and that probably also https://github.com/jasp-stats/INTERNAL-jasp/issues/921 is solved?

**Comment by FransMeerhoff** [comment]
@EJWagenmakers : Could you check if the problem still exits on the Windows nightly?

**Comment by FBartos** [comment]
Not sure how should I try it @FransMeerhoff . I build JASP using stable and the bug is still there.

**Comment by JorisGoosen** [comment]
@FBartos yeah it depends on how and where it is built. You should check [a nightly](https://static.jasp-stats.org/Nightlies/).

**Comment by FBartos** [comment]
thanks. I tested that using the Win64 .zip (https://github.com/jasp-stats/jasp-desktop/commit/aa58ce28119c95567fbdc35a0ed6ed63d8bc668a) and it still doesn't work.

**Comment by JorisGoosen** [comment]
On my system both the latest zip and msi work fine.

I will try on a korean system as well.

**Comment by JorisGoosen** [comment]
Ok, so on a korean windows I also get "Mathôt"...

@FBartos could you maybe try again and with an msi?
Otherwise I'm afraid I'm going to have to make a czech windows VM...

**Comment by FBartos** [comment]
hmm, I found an interesting interaction of problems (that's the same across released 13.1 and the nightly):

"Mathôt" alone is working
`estimatesTable <- createJaspTable(title = gettext("Estimation Summary (Mathôt) "))`
![image](https://user-images.githubusercontent.com/38475991/89285280-5d580a00-d650-11ea-897a-d9a95c646ef3.png)

"μ" alone is not working
`estimatesTable <- createJaspTable(title = gettext("Estimation Summary (\u03B8)"))`
![image](https://user-images.githubusercontent.com/38475991/89285400-8f696c00-d650-11ea-986c-4d0b755da68a.png)

unless it's in `gettextf`
`estimatesTable <- createJaspTable(title = gettextf("Estimation Summary (%s)", "\u03B8"))`
![image](https://user-images.githubusercontent.com/38475991/89285474-b9bb2980-d650-11ea-876d-24ab5f5ca90d.png)

However, "Mathôt" & "μ" makes both not working
`estimatesTable <- createJaspTable(title = gettextf("Estimation Summary (\u03B8) (Mathôt)"))`
![image](https://user-images.githubusercontent.com/38475991/89285865-6f867800-d651-11ea-85ff-eacd754fd7f2.png)

even if "μ" or both of "μ" and "Mathôt" are in `gettextf`, "Mathôt" fails, but differently
`estimatesTable <- createJaspTable(title = gettextf("Estimation Summary (%s) (Mathôt)", "\u03B8"))`
or `estimatesTable <- createJaspTable(title = gettextf("Estimation Summary (%s) (%s)", "\u03B8", "Mathôt"))`
![image](https://user-images.githubusercontent.com/38475991/89285630-03a40f80-d651-11ea-92be-0ecb4289abb0.png)

**Comment by JorisGoosen** [comment]
It still is weird that it *does* work on a korean system and not on a czech one though...

**Comment by FBartos** [comment]
@JorisGoosen all of the examples above work on the Korean and English, or only the first one?

**Comment by JorisGoosen** [comment]
Aah I did not check your examples yet.
(It is pretty annoying to work in a korean windows as I can't read most texts :p)

**Comment by FBartos** [comment]
I kinda suspect that anything but 1) won't work even in the English one and that we were just using an incorrect example for testing (the first one which you were using works in Czech too)

**Comment by boutinb** [comment]
@FransMeerhoff, @FBartos , @JorisGoosen: can this issue still be solved for 0.14 (next week, we should stop all development on 0.14). If not it has to be postponed to 0.15

**Comment by FBartos** [comment]
I'm not sure, but the issue seems to be just on my laptop (i.e., other people can see the "≤" in figures whereas I can't. I'm building a new PC next week and it will hopefully fix it.

**Comment by boutinb** [comment]
It is maybe a font problem... I have just merged a PR where you can change the fonts of the results or the interface.

**Comment by TimKDJ** [comment]
I've not seen a fix to this problem (it's because of UTF-8 problems on Windows with gettext). Any unicode in gettext is hidden from the user. It's actually a massive problem that cannot be pushed to 0.15, which is why I repeatedly put so much emphasis on solving this.

@boutinb open the following file and refresh it on MacOS:
[unicode-problems-windows.zip](https://github.com/jasp-stats/jasp-issues/files/5140836/unicode-problems-windows.zip)

Now compare it to this:
![unicode-missing](https://user-images.githubusercontent.com/18737241/91536863-b0eb0a00-e915-11ea-8fc9-b968a3eb5670.png)

**Comment by FBartos** [comment]
@boutinb changing fonts doesn't fix the disappearing  "≤" in figures

**Comment by vandenman** [comment]
@boutinb the fonts for the interface are completely separate from the fonts that R uses for plots. R currently looks at the system default and uses whatever font that is.

@FBartos if you've got some spare time, you could try out https://github.com/jasp-stats/jasp-desktop/pull/4219 to see if that works for you. That PR should allow you to specify a custom font for the plots.

**Comment by FBartos** [comment]
@vandenman thanks, I will check it next week
