### ISSUE TITLE
Reliability

### ISSUE THREAD

**Issue by ksteppler** [jasp-stats/jasp-issues#870]
* JASP version: 0.12.2

* OS name and version: Windows 10 Home
* Analysis: Reliability Cronbach's alpha
* Bug description: When I try to run my reliability test it gives me this error. 
![image](https://user-images.githubusercontent.com/68024466/86948564-89907180-c10a-11ea-997d-4ae1abbc74f9.png)

I have narrowed the problem down to errors in two columns from the data (v5 and v8). 
![image](https://user-images.githubusercontent.com/68024466/86949109-6adeaa80-c10b-11ea-8a32-14e27e68001c.png)

* Expected behaviour: I believe the error occurs when all numbers in those columns are the same (making them have 0 standard deviation). When I tested this theory and changed my data, that appeared to be a solution. I cannot change my data for my study so I am trying to determine what I need to do to continue.  

#### Steps to reproduce:
1. Go to 'descriptives'
2. Click on 'reliability'
3. Scroll down to 'cronbach's alpha: select v1(3pts)-v13'

**Comment by juliuspf** [comment]
Can you try updating your JASP to the newer version 0.13?

**Comment by juliuspf** [comment]
I am almost certain this is fixed in 0.13.0, so I am going to close it, please reopen when the problem resurfaces.

**Comment by ksteppler** [comment]
This did not fix the problem. Instead, it still tells me the variance is 0 for v5 and v8, but now it won't let me run the test without those two columns.

**Comment by ksteppler** [comment]
This did not fix my problem. It still says the variance is 0.

Thanks,
Kyla Steppler

**Comment by AlexanderLyNL** [comment]
Could you please add the jasp file as a zip to this thread?

**Comment by ksteppler** [comment]
I have a few that I need it for, but here is one of them.

Thanks,
Kyla Steppler

**Comment by juliuspf** [comment]
Did you mean to include a file? Anyhow, I know that the error handling does prevent variables that have a variance of 0 being entered into the analysis, because this breaks the check if variables are correlated negatively with the scale (at least that is the first thing it breaks).

**Comment by juliuspf** [comment]
@AlexanderLyNL If the user is set on including a variable that has no variance into the analysis, an option would be to make the check how variables are correlated with the scale optional. I would have to check what this means for the rest of the analysis. What do you think?

**Comment by juliuspf** [comment]
Okay, I checked it, and adding variables with variance of zero leads to a non-invertible covariance matrix, which breaks some coefficients. Thus, so far such variables cannot be included in the analysis.

**Comment by EJWagenmakers** [comment]
Yeah that makes sense, they should not be included. If such a case is detected, an appropriate warning should be given (e.g., "Variable XYZ has zero variance. Remove XYZ to continue."

**Comment by juliuspf** [comment]
this is what we do: 
<img width="479" alt="Screenshot 2020-07-10 at 12 17 54" src="https://user-images.githubusercontent.com/38500953/87144058-7666d880-c2a7-11ea-85a6-7cbde658bcab.png">

**Comment by AlexanderLyNL** [comment]
I agree, it's reasonable to throw an error if the variance is zero.
